### ISSUE TITLE
elixir format error (linux, elixir1.8)

### ISSUE THREAD

**Issue by tt67wq** [elixir-editors/emacs-elixir#435] opened 2019-06-11 00:27 UTC
I installed elixir 1.8 by asdf, and mix in shims is
```
#!/usr/bin/env bash
# asdf-plugin: elixir 1.8
exec /home/manjaro/.asdf/bin/asdf exec "mix" "$@"
```
and when I do the function elixir-format, it gave an error
```
** (SyntaxError) /home/manjaro/.asdf/shims/mix:3: syntax error before: '.'
    (elixir) lib/code.ex:767: Code.require_file/2
```
when I changed mix to 
```
#!/usr/bin/env elixir
# asdf-plugin: elixir
Mix.start
Mix.CLI.main
```
it works.

I saw the code, elixir-format is running ['elixir', 'mix', 'format', 'path'], so when mix is a shell script, it gave a syntax error, can we change elixir-format to ['mix', 'format', 'path']?

**Comment by gabrielelana** [comment] 2019-06-22 09:39
Duplicate of #431

**Comment by tt67wq** [comment] 2019-06-22 12:42
> Duplicate of #431

thanks

**Closed** 2019-08-31 22:25 UTC
